version: '3'

services:
  devops-mysql:
    platform: linux/x86_64
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=timesheet-devops-db
    ports:
      - "3306:3306"
  devopsimage:
    image: houssemferjani/timesheetdevops:latest
    depends_on:
      - devops-mysql
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: jdbc:mysql://devops-mysql:3306/timesheet-devops-db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: root
      spring.datasource.password: root
    build:
      context: "./"
      dockerfile: Dockerfile
networks:
  reseau:
